version: "3.9"

services:

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py test && python manage.py update_airports && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/AerLabs
    ports:
      - "8000:8000"